myapp/App_Main/urls.py
from django.urls import path
from . import views
app_name='App_Main'
urlpatterns = [
path('', views.order,name='main'),
path('parcel/', views.create_parcel,name='parcel'),
path('deliver_parcel/<pk>/', views.deliver_parcel,name='deliver_parcel'),
path('my_orders/', views.merchant_orders,name='my_orders'),
]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Login.urls')),
    path('main/', include('App_Main.urls')),
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/App_Main/models.py
from django.db import models
from App_Login.models import  User,Merchant

# Create your models here.

class Location(models.Model):
    location=models.CharField(max_length=50)
    class Meta:
        verbose_name_plural='Location'
        db_table = 'Location'
    
    def __str__(self):
        return self.location    



class Parcel(models.Model):
    TYPE = (
        ('F', 'Fragile'),
        ('L', 'Liquid'),
    )
    parcel_weight=models.IntegerField(default=0)
    parcel_type=models.CharField(max_length=1,choices=TYPE)
    parcel_cost=models.IntegerField(default=0)
    parcel_cod_charge=models.IntegerField(default=0)
    parcel_return_charge=models.IntegerField(default=0)
    parcel_deliver_to=models.ForeignKey(Location,on_delete=models.CASCADE,related_name='deliver_to')
    added_for_delivery=models.BooleanField(default=False)
    class Meta:
        verbose_name_plural='Parcel'
        db_table = 'Parcel'

    
    
    

class Order(models.Model):
    orderer=models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_orderer')
    merchant=models.ForeignKey(Merchant,on_delete=models.CASCADE,related_name='merchant')
    parcel=models.ForeignKey(Parcel,on_delete=models.CASCADE,related_name='parcel')
    merchant_invoice_id=models.CharField(max_length=10)
    order_id=models.CharField(unique=True,max_length=10)
    ordered=models.BooleanField(default=False)   
    class Meta:
        verbose_name_plural='Order Table'
        db_table = 'Order Table'

    def __str__(self):
        return self.orderer.username+'   Ordered   '+ self.merchant.user.username +" "+self.order_id

myapp/App_Main/forms.py
from django import forms
from django.forms import ModelForm
from App_Login.models import Merchant
from . import models


class OrderForm(forms.ModelForm):
    query_list = Merchant.objects.all()
    merchant = forms.ModelChoiceField(
        queryset=query_list,
        label="Select Merchant:",
        required=True,
        to_field_name='user',
        empty_label="Select Merchant",
        widget=forms.Select(attrs={"class": "form-control mb-3"}),
    )
    merchant_invoice_id = forms.CharField(
        required=True,
        label='Enter The InVoice Id For your Merchant:',
        widget=forms.TextInput(
            attrs={
                "placeholder": "Enter Merchant InVoice Id to Confirm Order",
                "class": "form-control mb-3",
            }
        ),
    )

    class Meta:
        model = models.Order
        fields = (
            "merchant",
            "merchant_invoice_id",
        )


class ParcelForm(forms.ModelForm):
    TYPE = (
        ("F", "Fragile"),
        ("L", "Liquid"),
    )
    parcel_weight = forms.IntegerField(
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Enter Your Parcels Weight(In Kg, 2,3,4,5)",
                "class": "form-control mb-3",
            }
        ),
    )
    parcel_type = forms.ChoiceField(
        required=True,
        choices=TYPE,
        widget=forms.Select(attrs={"class": "form-control mb-3"}),
    )
    parcel_deliver_to = forms.ModelChoiceField(
        queryset=models.Location.objects.all(),
        label="Select Delivery Place:",
        required=True,
        to_field_name='location',
        empty_label="Select Delivery Place",
        widget=forms.Select(attrs={"class": "form-control mb-3"}),
    )

    class Meta:
        model = models.Parcel
        exclude = ("added_for_delivery",'parcel_cost','parcel_cod_charge','parcel_return_charge',)

myapp/App_Main/views.py
from django.shortcuts import render
from . import models,forms
from App_Login.models import Merchant
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from django.contrib import messages
from django.urls import reverse,reverse_lazy
import uuid

# Create your views here.
def order(request):
    orders=models.Order.objects.filter(orderer=request.user,ordered=True)
    return render(request,'App_Main/Orders.html',context={'orders':orders,'title':'Your Orders'})

def insidedhaka(weight):
    if weight >= 0.5 and weight <= 2:
        cost=60 
    elif weight== 3:
        cost=70 
    elif weight== 4:
        cost=80 
    elif weight== 5:
        cost=90 
    else:
        cost=0
    cod_charge=cost*0
    return_charge=cost*0
    return cost,cod_charge,return_charge

def dhaka(weight):
    if weight >= 0.5 and weight <= 2:
        cost=110 
    elif weight== 3:
        cost=130 
    elif weight== 4:
        cost=150 
    elif weight== 5:
        cost=170
    else:
        cost=0
    cod_charge=cost*0.1
    return_charge=cost*0.5
    return cost,cod_charge,return_charge

def outsidedhaka(weight):
    if weight >= 0.5 and weight <= 2:
        cost=130 
    elif weight== 3:
        cost=150 
    elif weight== 4:
        cost=170 
    elif weight== 5:
        cost=190
    else:
        cost=0
    cod_charge=cost*0.1
    return_charge=cost*0.5
    return cost,cod_charge,return_charge



def create_parcel(request):
    form=forms.ParcelForm()
    parcels=models.Parcel.objects.filter(added_for_delivery=False)
    cod_charge=0
    return_charge=0
    cost=0
    if request.method=='POST':
        form=forms.ParcelForm(request.POST)
        if form.is_valid():
            parcel_weight=form.cleaned_data.get('parcel_weight')
            parcel_deliver_to=form.cleaned_data.get('parcel_deliver_to')
            parcel_deliver_to=str(parcel_deliver_to)
            parcel_weight=int(parcel_weight)
            form=form.save(commit=False)
            if parcel_deliver_to=='Inside Dhaka':
               cost,cod_charge,return_charge=insidedhaka(parcel_weight)
            elif parcel_deliver_to=='Dhaka':
                cost,cod_charge,return_charge=dhaka(parcel_weight)
            elif parcel_deliver_to=='Outside Dhaka':
                cost,cod_charge,return_charge=outsidedhaka(parcel_weight)
            form.parcel_cod_charge=cod_charge
            form.parcel_return_charge=return_charge
            form.parcel_cost=cost+cod_charge+return_charge
            form.save()
            messages.success(request,'Parcel Created Successfully')
            return HttpResponseRedirect(reverse('App_Main:parcel'))
    return render(request,'App_Main/CreateParcel.html',context={'form':form,'title':'Create a New Parcel','parcels':parcels})

def deliver_parcel(request,pk):
    form=forms.OrderForm()
    user=request.user
    parcels=models.Parcel.objects.filter(added_for_delivery=False,pk=pk)
    if request.method=='POST':
        form=forms.OrderForm(request.POST)
        if form.is_valid():
            merchant_invoice_id=form.cleaned_data.get('merchant_invoice_id')
            verify_merchant=Merchant.objects.filter(invoice_id=merchant_invoice_id)
            if verify_merchant.exists():
                form=form.save(commit=False)
                if parcels.exists():
                    parcel=parcels[0]
                    parcel.added_for_delivery=True
                    parcel.save()
                    form.parcel=parcel
                if user.is_superuser:
                    form.orderer=user
                form.ordered=True
                form.order_id=str(uuid.uuid4())[:10]
                form.save()
                messages.success(request,'Parcel Added to Order.....')
            else:
                messages.warning(request,'Unable To Verify Merchant. Please Check Merchants Invoice id')    
            return HttpResponseRedirect(reverse('App_Main:parcel'))
    return render(request,'App_Main/DeliverParcel.html',context={'form':form,'title':'Deliver This Parcel','parcels':parcels})



def merchant_orders(request):
    merchant=Merchant.objects.get(user=request.user)
    orders=models.Order.objects.filter(merchant=merchant,ordered=True)
    return render(request,'App_Main/MerchantOrders.html',context={'title':'My Orders','orders':orders})

myapp/templates/App_Main/CreateParcel.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block body_block %}
  <h1 class="text-center my-4">{{title}}</h1>
  <div class="container">
      <div class="row">
          <div class="col-sm-6">
            <form method="post">
                {% csrf_token %}
              {% for field in form %}
                  {{ field.errors }}
                  <label for="{{field.id_for_label}}" class="form-label"> {{field.label}}</label>
                  {{ field }}
                  {% if field.help_text %}
                  <p class="help">{{ field.help_text|safe }}</p>
                  {% endif %}
          {% endfor %}
          
          <input type="submit" value="Create" class="btn buttoncustom my-3">
          
            </form>

          </div>
          <div class="col-sm-6">
            {% for parcel in parcels %}

            <div class="col mb-2">
                    <div class="card p-3">
                        <div class="card-body">
                            <h3 class="card-title text-center"> Deliver to - {{parcel.parcel_deliver_to}}
                            </h3>                            
                            <h5 class="card-title text-center">Parcel Type-  {{parcel.parcel_type}}
                            </h5>                            
                            <h5 class="card-title text-center">Parcel Cost- {{parcel.parcel_cost}} TK
                            </h5>
                        </div>
                        <a class="btn buttoncustom" href="{% url 'App_Main:deliver_parcel' pk=parcel.pk %}" > Deliver This Parcel</a>
                    </div>
            </div>
            {% empty %}
            <h3 class="justify-center text-center mt-4">No UnOrdered Parcels.<br/>Create A New Parcel.</>
            {% endfor %}
          </div>
      </div>
  </div>
  
{% endblock body_block %}

myapp/templates/App_Main/DeliverParcel.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block body_block %}
  <h1 class="text-center my-4">{{title}}</h1>
  <div class="container">
      <div class="row">
          <div class="col-sm-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
           {{form|crispy}}
          <input type="submit" value="Deliver Parcel" class="btn buttoncustom my-3">
            </form>

          </div>
          <div class="col-sm-6">
            <h2 class='text-center my-3'>Parcel Details</h2>
            {% for parcel in parcels %}

            <div class="col mb-2">
                    <div class="card p-3">
                        <div class="card-body">
                            <h3 class="card-title text-center"> Deliver to - {{parcel.parcel_deliver_to}}
                            </h3>                            
                            <h5 class="card-title text-center">Parcel Type-  {{parcel.parcel_type}}
                            </h5>
                            <p>Cost - {{parcel.parcel_cost}} Tk</p>
                            <p>COD Charge - {{parcel.parcel_cod_charge}} Tk</p>
                            <p>Return Charge - {{parcel.parcel_return_charge}} Tk</p>
                        </div>
                    </div>
            </div>
            {% endfor %}
          </div>
      </div>
  </div>
  
{% endblock body_block %}

myapp/templates/App_Main/MerchantOrders.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block body_block %}
<h1 class="text-center my-4">{{title}}</h1>
<div class="container">
    <table class="table table-dark table-hover">
        <thead>
            <tr>
              <th scope="col">SN</th>
              <th scope="col">Order_ID</th>
              <th scope="col">Merchant</th>
              <th scope="col">Merchant_Invoice_Id</th>
              <th scope="col">Deliver To</th>
              <th scope="col">Price</th>
            </tr>
          </thead>
          <tbody>
            {% for parcel in orders %}
            
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td >{{parcel.order_id}}</td>
              <td >{{parcel.merchant.user.username}}</td>
              <td >{{parcel.merchant_invoice_id}}</td>
              <td >{{parcel.parcel.parcel_deliver_to}}</td>
              <td>{{parcel.parcel.parcel_cost}}</td>
            </tr>
            
            {% endfor %}
          </tbody>
      </table>
    </div>
</div>

{% endblock body_block %}

myapp/templates/App_Main/Orders.html
{% extends "Base.html" %}
{% load crispy_forms_tags %}
{% block body_block %}
<h1 class="text-center my-4">{{title}}</h1>
<div class="container">
    <table class="table table-dark table-hover">
        <thead>
            <tr>
              <th scope="col">SN</th>
              <th scope="col">Order_ID</th>
              <th scope="col">Merchant</th>
              <th scope="col">Merchant_Invoice_Id</th>
              <th scope="col">Deliver To</th>
              <th scope="col">Price</th>
            </tr>
          </thead>
          <tbody>
            {% for parcel in orders %}
            
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td >{{parcel.order_id}}</td>
              <td >{{parcel.merchant.user.username}}</td>
              <td >{{parcel.merchant_invoice_id}}</td>
              <td >{{parcel.parcel.parcel_deliver_to}}</td>
              <td>{{parcel.parcel.parcel_cost}}</td>
            </tr>
            
            {% endfor %}
          </tbody>
      </table>
    </div>
</div>

{% endblock body_block %}