myapp/App_Login/urls.py
from django.urls import path
from . import views
app_name='App_Login'
urlpatterns = [
path('', views.HomeView.as_view(),name='home'),
path('signup/', views.signupview,name='signup'),
path('login/', views.login_view,name='login'),
path('profile_update/', views.merchant_profile_change,name='profile_update'),
path('logout/', views.logout_view,name='logout'),
]

myapp/App_Main/urls.py
from django.urls import path
from . import views
app_name='App_Main'
urlpatterns = [
path('', views.order,name='main'),
path('parcel/', views.create_parcel,name='parcel'),
path('deliver_parcel/<pk>/', views.deliver_parcel,name='deliver_parcel'),
path('my_orders/', views.merchant_orders,name='my_orders'),
]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Login.urls')),
    path('main/', include('App_Main.urls')),
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/templates/Base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type='text/css' href="{% static 'css/base.css' %}">
    <title> Courier Delivery System </title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&display=swap');

        body {
            font-family: 'Open Sans', sans-serif;
        }
    </style>

</head>

<body>
    <div class="container-fluid py-3 topbar">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h2>Courier Delivery System</h2>
            </div>
        </div>

    </div>
    <nav class="navbar navbar-custom">
        <div class="container">
            <div>
                <ul class="nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'App_Login:home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated and user.is_merchant %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Login:profile_update' %}" title={{user.username}}>My
                            Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Main:my_orders' %}">View Orders</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
                    </li>
                    {% elif user.is_authenticated and user.is_staff and user.is_active %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Main:main' %}">Admin orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Main:parcel' %}">Create A New Parcel</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
                    </li>

                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Login:signup' %}">SignUp</a>
                    </li>
                    {% endif %}
            </div>
        </div>
    </nav>
    {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show {% endif %}"
        role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">&times;</button>
    </div>
    {% endfor %}
    {% endif %}
    <div class="container">
        {% block body_block %}
        {% endblock body_block %}

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>

</body>

</html>